name: tests

on:
  push:
    branches:
      - main
  pull_request: null

concurrency:
  group: tests

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          environment-file: test-env.yml
          lock-file: conda-lock.yml
          ignored-packages: ''
          relock-all-packages: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          automerge: false

      - name:
        shell: bash
        run: |
          if [ -f conda-lock.yml ]; then
            :  # do nothing
          else
            echo "conda-lock.yml not found"
            exit 1
          fi
          grep numpy conda-lock.yml
          grep python conda-lock.yml
